apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: custom-notebook
  namespace: custom-notebook-demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'custom-notebook:latest'
  source:
    git:
      ref: main
      uri: 'https://github.com/JeetRH/JupyterH.git'
    type: Git
    #contextDir: notebook
  strategy:
    type: Docker
#     dockerStrategy:
#       from:
#         kind: ImageStreamTag
#         name: 's2i-generic-data-science-notebook:v0.0.5'
  triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
